### ISSUE TITLE
bugs 0.4.1

### ISSUE THREAD

**Issue by t0nym0n0** [grindylow/ahoy#39]
Hallo Leute,

in der version 0.4.1. passt bei meinem HM600 der Wert YieldDay auf dem CH2 nicht mehr. Es wird nur 1.0 Wh angezeigt.
Ebenfalls wird bei meinem HM350 der CH2 im Webinterface angezeigt...

**Comment by gymnae** [comment]
Bei mir sendet YieldDay auf CH1 abwechselnd den Wert, der auch im Web interface gezeigt wird oder einen viel kleineren Wert, den ich im Web interface nicht sehe
EDIT: Nach Update von 0.4.0 zu 0.4.1 via OTA werden für meinen HM800 keine Werte mehr bei CH1 oder CH0 angezeigt.

**Comment by lumapu** [comment]
ok, wie sieht euere Payload auf der Seriellen Konsole aus? Kommt da was?
@t0nym0n0 Ich glaube die Bytezuordnung ist falsch - das kann gut sein, da ich keinen der Inverter zum testen habe.
@Gymnae Das klingt komisch, auch hier wäre interessant was die Serielle Konsole spricht. Deine Seriennnummer fängt mit 1141 an?

**Comment by gymnae** [comment]
> ok, wie sieht euere Payload auf der Seriellen Konsole aus? Kommt da was? @t0nym0n0 Ich glaube die Bytezuordnung ist falsch - das kann gut sein, da ich keinen der Inverter zum testen habe. @Gymnae Das klingt komisch, auch hier wäre interessant was die Serielle Konsole spricht. Deine Seriennnummer fängt mit 1141 an?

EDIT: Ich war dumm, ich habe bei der Eintragung eine 1 vergessen...

**Comment by AsZork** [comment]
Kleiner Zuordnungsfehler in

    { FLD_YD,  UNIT_WH,  CH2, 24, 2, 1    },
    { FLD_YD,  UNIT_KWH, CH2, 18, 4, 1000 },

**Comment by gymnae** [comment]
Works perfectly, thank you
