### ISSUE TITLE
MQTT - only report if data has been actually received

### ISSUE THREAD

**Issue by Argafal** [grindylow/ahoy#55]
Current behaviour: If one out of multiple inverters is offline (e.g. one inverter gets unplugged), ahoy shows all values of the unplugged inverter as zeros. Ahoy also sends those zeros on MQTT. This is probably caused by the data from the other (online) inverters setting the mMqttNewDataAvailable boolean to true. 

Expected behaviour: Instead of showing zeros, ahoy should show that this one inverter is offline. At the very least, the displayed values should not be zero but "n/a" or -1 or the like, something that clearly shows that the values of this inverter are invalid. Nothing should be reported on MQTT in this situation. This will allow the downstream MQTT receiver to flag the inverter as offline/"no recent data received".

**Comment by lumapu** [comment]
ok understand. Then the flag must be dependent on the inverter.
The offline/online information is already there, I'll introduce a new MQTT field which shows the current online status.

I think there are other issues while disconnecting one of the defined inverters. For now I spent no time on debugging this.

**Comment by lumapu** [comment]
fixed in 0.4.13
